### PR TITLE
Add option to show document id if total count in cluster is 1

### PR DESCRIPTION
**Pull request by CGenie**
When 1 element is returned in faceting, return it's `_id` property too. That way we can localize it via the GET api and return additional info for it on pins, for example.

### CODE REVIEW

**Comment by popovae** [comment]
Hello CGenie! Did you find any way to do it?

**Comment by CGenie** [comment]
Hello,
Well, are you asking about commit https://github.com/CGenie/geohash-facet/commit/0c2aecf230bbb53ff89a81364c135b746c717fe5 ?

**Comment by popovae** [comment]
Hello! Thank you and sorry, I'm new to github)

**Comment by RapotOR** [comment]
Hello,

Nice! That's a missing feature for sure.
Is it possible to make it more configurable? 
Like having an option to retrieve a defined number of document's ID for each markers.
Or an option to retrieve document's ID if the marker count is inferior to a defined number.

Anyway, the commit is already valuable! Thanks.

**Comment by CGenie** [comment]
@RapotOR  I guess this is possible, but I don't have much time right now. I'll add this to my todo list though :)

**Comment by popovae** [comment]
Sorry for a stupid questions, but i see the names of the files needed to be edited, but I can find them on server...сфт you please tell me where are they located?

**Comment by ginaluca** [comment]
Hi @CGenie ,

I'm definitely going to merge this. Only I'll need to do it manually because my code base has changed too much in the meanwhile.

@RapotOR : returning more than one id might make the facet too memory intensive, so for now I prefer to stick with simple feature.

**Comment by fbertheuil** [comment]
Hello,

i'm really looking for this feature, when do you think it w'll be available ?

Thank a much.

**Comment by RapotOR** [comment]
@ginaluca 
Ok, I understand. One id is already a nice feature. Thank you.

In my opinion, the memory consumption should be taken in account by the application owner.
For example, I am using a filter based on the map box and a geohash-facet factor adapted to the map zoom. So, the marker count is never really high; only big numbers on each marker. Markers with a count lower than 5 (an example) only appears for zoom on a well-defined area. So, i think it will not be so memory consuming.

I dont know very well Java but I will try to implement those options; at least to see the memory impact.

Regards,

**Comment by gennadys** [comment]
Hi,
When are you planning next update with this feature?

**Comment by ginaluca** [comment]
Hi,
I'll try to have a new release by the end of next week.

Greetings,
  Gianluca

**Comment by ginaluca** [comment]
Released 0.0.15

**Pull request closed without merging**
